trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: MavenAuthenticate@0
  inputs:
    artifactsFeeds: 'my-nuget-feed'

- script: |
    echo "Setting execute permissions for project chromedriver..."
    chmod +x src/test/resources/chromedriver/chromedriver
    echo "Verifying Chrome and project's ChromeDriver versions:"
    google-chrome --version
    echo "Project's ChromeDriver version:"
    src/test/resources/chromedriver/chromedriver --version
  displayName: 'Set Permissions & Verify Chrome/ChromeDriver Versions'
  
- script: |
    google-chrome --version
    chromedriver --version
  displayName: 'Verify Chrome versions'
  
# Ejecutar pruebas Maven + Serenity
- task: Maven@3
  displayName: 'Build and Run Tests'
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'clean verify'  # Solo ejecuta pruebas, sin generar el reporte aún

- task: Maven@3
  displayName: 'Generate Serenity Report'
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'serenity:aggregate'  # Genera el reporte HTML después
    options: '-DskipTests=true'  # Evita re-ejecutar pruebas
  condition: succeededOrFailed()  # Genera el reporte incluso si fallan las pruebas

# Publicar reporte Serenity (aunque falle la build)
- task: PublishBuildArtifacts@1
  condition: succeededOrFailed()
  inputs:
    PathtoPublish: 'target/site/serenity'
    ArtifactName: 'SerenityReport'
    publishLocation: 'Container'
